application: clouddashboard-1208
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "latest"


builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static

env_variables:
  DJANGO_SETTINGS_MODULE: 'bookshelf.settings'